services:
  - type: web
    name: uptut
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: APP_URL
        value: https://uptut.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: uptut-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: uptut-redis
          property: connectionString

  - type: redis
    name: uptut-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

  - type: postgres
    name: uptut-db
    ipAllowList: []
    plan: free
    postgresMajorVersion: 15 